[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
drift_voter_plugin = "HWGVLwZnTRrKp8Ex4U6oJwXriZcsXJvWCE9PZUioPksh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/fish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
