[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
drift-stake-voter = "3o99FELvs9dNUL7eXPX913u33CRhkxLDmwZaEZ7ATP8P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/fish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
